name: Node App CI

on:
 pull_request:
    types: [opened, reopened]
    branches: [develop, master]
    # paths:
    #   - 'nodeapp/**'
    
env:
  NODE_VERSION: '16.x'


jobs:

  Job1-Build-NodeApp:
    name: Node App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nodeapp
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Detect File changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'nodeapp/**'

    - name: Exit Workflow if Node App has no changes
      if: steps.changes.outputs.src == 'false'
      run: exit 1
      
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
       
    - name: Install App dependencies
      run: npm ci

    - name: Run Unit Tests
      id: runtests
      run: npm test
      env:
          CI: true

    - name: Deploy Unit Test Report to GitHub Page (if Unit tests fail)
      # if: ${{ always() && (steps.runtests.conclusion == 'success') }}
      if: ${{ always() && (steps.runtests.outcome == 'failure' || steps.runtests.outcome == 'success') }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.SEMANTIC_TOKEN }}
        publish_dir: ./nodeapp/reports
        publish_branch: gh-pages
 
    - name: Run Tests Coverage
      # if: ${{ always() && (steps.runtests.conclusion == 'success') }}
      if: ${{ always() && (steps.runtests.outcome == 'failure' || steps.runtests.outcome == 'success') }}
      id: runcoverage
      run: npm run test:coverage
      env:
          CI: true

    - name: Deploy Test Coverage Report to GitHub Page (if Unit tests fail)
      if: ${{ always() && (steps.runcoverage.outcome == 'failure' || steps.runcoverage.outcome == 'success') }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.SEMANTIC_TOKEN }}
        publish_dir: ./nodeapp/coverage
        publish_branch: gh-pages
        destination_dir: ./coverage
        keep_files: false

    - name: Create an Issue (if Unit tests fail)
      if: ${{ always() && (steps.runtests.outcome == 'failure' || steps.runcoverage.outcome == 'failure') }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
        TITLE: Node App Tests/Coverage Failed
        LABELS: test
      with:
        filename: .github/ISSUE_TEMPLATE.md
        assignees: ${{github.actor}}

    # - name: Create an Issue (if Unit tests fail)
    #   if: ${{ always() && (steps.runtests.outcome == 'failure' || steps.runcoverage.outcome == 'failure') }}
    #   uses: nashmaniac/create-issue-action@v1.1
    #   with:
    #     title: Node App Tests/Coverage Failed
    #     token: ${{secrets.SEMANTIC_TOKEN}}
    #     assignees: ${{github.actor}}
    #     labels: nodeapp-test-failed
    #     body: "[Check test report here.](https://creativehub2000.github.io/Mono1/index.html)"


    - name: Do other steps (If all previous steps were success)
      if: ${{ success() }}
      run: echo "Do other steps here..."

    # - name: Dump context
    #   uses: crazy-max/ghaction-dump-context@v1
  
  Job2-Create-Issue:
    name: Create Issue
    runs-on: ubuntu-latest
    needs: [Job1-Build-NodeApp]

    steps:

    - name: Do other steps
      run: echo "Do other steps here..."

    - name: Dump context
      uses: crazy-max/ghaction-dump-context@v1

  # Job2-Create-Issue:
  #   name: Create Issue
  #   runs-on: ubuntu-latest
  #   if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
  #   needs: [Job1-Build-NodeApp]

  #   steps:
  #   - name: Create Issue
  #     uses: nashmaniac/create-issue-action@v1.1
  #     with:
  #       title: Automated Issue from workflow
  #       token: ${{secrets.SEMANTIC_TOKEN}}
  #       assignees: ${{github.actor}}
  #       labels: test-failed
  #       body: "[Test Report is out.](https://creativehub2000.github.io/Project1/index.html)"
       
