name: React App CI

# on:
#  workflow_run:
#     workflows: [Node App CI]
#     types: [completed]
#     branches: [develop, master]
#     paths: ['reactapp/**']
on:
 pull_request:
    types: [opened, reopened]
    branches: [develop, master]
    paths: ['reactapp/**']

jobs:

  Job1-Build-ReactApp:
    name: React App
    runs-on: ubuntu-latest

    steps:
    - name: Do other steps
      run: echo "Do other steps here..."
