name: React App CI

# on:
#  workflow_run:
#     workflows: [Node App CI]
#     types: [completed]
#     branches: [develop, master]

on:
 pull_request:
    types: [opened, reopened]
    branches: [develop, master]
    # paths: 
      # - 'reactapp/**'

env:
  NODE_VERSION: '16.x'


jobs:

  Job1-Build-ReactApp:
    name: React App
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Detect File changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'reactapp/**'

    - name: Exit Workflow if React App has no changes
      if: steps.changes.outputs.src == 'false'
      run: exit 1

    - name: Do other steps
      run: echo "Do other steps here..."

    - name: Deploy Test Report to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.SEMANTIC_TOKEN }}
        publish_dir: ./reactapp/reports
        publish_branch: gh-pages
        destination_dir: ./react
        keep_files: false

